version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - default

  server:
    build: ./server
    ports:
      - "5000:5000"
    networks:
      - default

networks:
  default:
    driver: bridge
