name: Build Docker Images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Compose
        run: docker-compose build

      - name: Up Docker Compose
        run: docker-compose up -d

      - name: Test Docker Compose
        run: curl -s --retry 10 --retry-connrefused http://localhost:3000/

      - name: Down Docker Compose
        run: docker-compose down
